.PHONY: php\:dep
## Install dependencies
# TODO: Add options
php\:dep:
	composer install

.PHONY: php\:dep\:setup
# Install dependencies tool
php\:dep\:setup: $(PHP)
	@$(PHP) -r "readfile('https://getcomposer.org/installer');" | $(PHP)
	@mv composer.phar composer
	@chmod +x composer
	composer --version
